### ISSUE TITLE
Programatically stop spinner at a specific location

### ISSUE THREAD

**Issue by varundusane** [CrazyTim/spin-wheel#17]
can we stop spinner at specific location?  like programatically decide where to stop , no random

**Comment by CrazyTim** [comment]
@varundusane not currently. Its been on my mind and would be great to add this.

**Comment by pmoralesp** [comment]
> @varundusane not currently. Its been on my mind and would be great to add this.

Any hint to reach this? I could give a try

**Comment by CrazyTim** [comment]
@pmoralesp I have a work in progress 3.5 branch with this feature, check it out :)
