### ISSUE TITLE
Pass the output from the external API?

### ISSUE THREAD

**Issue by tv-ankur** [CrazyTim/spin-wheel#29]
Is it possible to pass the output from the external API? 

I have external API that return the result of wheel that I want to pass as the output into wheel. Is it possible?

**Comment by CrazyTim** [comment]
Hi @tv-ankur see the README for examples how to spin the wheel.

Is there something specific that you're not sure about? Feel free to post a code example of what you are trying to do so others can help.

**Comment by dsweb19778** [comment]
yes its possible u need to parse the response using JSON.parse if its a JSON format and get the value after that validate it and use wheel.spinToItem(value)
