### ISSUE TITLE
Don't allow stopping of a spinning wheel with touch or click

### ISSUE THREAD

**Issue by meshane** [CrazyTim/spin-wheel#34]
I like allowing the user to spin the wheel with a finger on a mobile device, but I don't want them to then stop it by touching the wheel in order to set the result they want.

**Comment by CrazyTim** [comment]
HI @meshane,

You should be able to do this by handling the `onSpin` event - simply set `isInteractive` to `false`.

**Comment by matronator** [comment]
@meshane and anyone else reading this in the future. To be clear, I think what @CrazyTim had in mind was to do something like this:

```js
wheel.onSpin(event => {
	wheel.isInteractive = false;
});

wheel.onRest(event => {
	wheel.isInteractive = true;
});
```
