### ISSUE TITLE
Implementing for Android Application

### ISSUE THREAD

**Issue by atesahmet0** [CrazyTim/spin-wheel#35]
Hi, I want to embed this on an Android Application. I'm no expert on Javascript and etc. but I do know few things. 

I've researched a bit and found out that maybe I can use Ionic in order to implement this on Android. Any help would be nice. Thanks in advance.

**Comment by CrazyTim** [comment]
Hi @atesahmet0, I don't know much about Android, but it sounds like you are on the right track. A good place to ask for help is on Discord.
