### ISSUE TITLE
Is there anyway to cut space between label and image in each item? 

### ISSUE THREAD

**Issue by elvinkim03** [CrazyTim/spin-wheel#36]

**Comment by CrazyTim** [comment]
@elvinkim03 can you provide a screenshot and example of what you are trying to do?

**Comment by elvinkim03** [comment]
@CrazyTim Sorry I was really busy. I've designed and changed to use image property now. But there's a problem sometime the image flick white when I try to change the image (I change to selected image that has highlighted) and I'm not sure what caused it

**Comment by CrazyTim** [comment]
Hi @elvinkim03, it sounds like the image has not been loaded by the browser yet. Try pre-loading all images before you add them to the wheel. Have a look at how its done in this example page https://crazytim.github.io/spin-wheel/examples/themes.
