### ISSUE TITLE
Unable to export as Json from the playground.

### ISSUE THREAD

**Issue by muhammadbasitobaid** [CrazyTim/spin-wheel#37]
Whenever I try to export Wheel with customized props, I'm unable to do so.
in the console it gives:
`Uncaught ReferenceError: wheelPropInits is not defined
    at HTMLButtonElement.exportWheelAsJson (initEventListeners.js:152:45)`
  This Repo has been of great help. I would really like to resolve this issue.
![image](https://github.com/CrazyTim/spin-wheel/assets/79991232/c74c6b38-a615-41e6-a4ee-9e96b450ee04)

**Comment by muhammadbasitobaid** [comment]
Leaving here for reference in https://github.com/CrazyTim/spin-wheel/blob/main/src/constants.js a constant is default exported contains all the Wheel props.

**Comment by CrazyTim** [comment]
@muhammadbasitobaid I have fixed in [36f378b](https://github.com/CrazyTim/spin-wheel/commit/36f378b6ffd66997330839482820dd13a3d4e053), thanks for raising the issue. Please hard refresh the page and it should be working now.
