### ISSUE TITLE
Infinite resize loop

### ISSUE THREAD

**Issue by DashBarkHuss** [CrazyTim/spin-wheel#46]
Resizing is looping and causing the spin wheel to never stop growing.
[code](https://codepen.io/czmax/pen/zYVwGmm?editors=1111)
```
ResizeObserver loop completed with undelivered notifications. 
 at https://cdpn.io/cpe/boomboom/index.html?editors=1111&key=index.html-dc5a19c1-132d-c34f-92cd-b979d90cd8a5:0
```

**Comment by CrazyTim** [comment]
Hi @DashBarkHuss, thanks for raising, it needs to be fixed. I think the wheel needs to be inside a container element that has a fixed size so `Wheel.resize()` will work properly.

Add this style to your example and this should fix it:

```
html, body, .wheel-container {
  height: 100%;
}
```

It would be great if we didn't need to do this! So I'll leave this ticket open as a bug.

**Comment by worldbiomusic** [comment]
I got the same issue and solved by set height to `px`. If height is `%` infinite resizing loop started.

```css
canvas {
  width: 100%;
  height: 400px;
}
```

**Comment by CrazyTim** [comment]
@worldbiomusic exactly! It's fine if the container's size is constrained, otherwise I think the resize method causes a positive feedback loop.

**Comment by CrazyTim** [comment]
@DashBarkHuss this has been fixed in https://github.com/CrazyTim/spin-wheel/commit/c1f425e11fcd1a474f2a31172a180ddc11137738.
