### ISSUE TITLE
rotationResistance = 0 in Safari

### ISSUE THREAD

**Issue by kuhdmitry** [CrazyTim/spin-wheel#51]
I need to make infinity spinning. But after some time I get an error in Safari (when option **rotationResistance: 0**)

`CanvasRenderingContext2D.save() has been called without a matching restore() too many times. Ignoring save().`

<img width="963" alt="screenshot_2024-10-01_19 24 21" src="https://github.com/user-attachments/assets/7f499f7d-1594-4f60-a76e-e5c18be8dca7">

**Comment by CrazyTim** [comment]
@kuhdmitry thanks for raising this. Should be fixed now 😄
